### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by takeyamayuki** [takeyamayuki/RESTuino#1]
# Tasks
- [x] digitalread  
- [ ] pullupread  
- [x] digitalwrite PUT  
- [ ] digitalwrite GET  
- [x] analogread  
- [x] ledcwrite (analogwrite for esp32)  
- [x] servo  
- [ ] touch  
- [ ] dacwrite  
- [x] eeprom save of settings   
- [x] eeprom load of settings   
- [x] Apply settings saved in eeprom   
- [ ] Multiple servo
- [ ] Multiple ledcwrite   
- [ ] I2C
- [ ] SPI
- [ ] UART
- [ ] Web GUI
- [ ] API test
- [ ] SSL support
- [ ] Ethernet support
- [x] arduino library
